version: '3'
services:
  app:
    build: ./
    env_file: .env
    volumes:
      - ./:/code
    ports:
      - 3000:3000
    tty: true
  sagemaker:
    build:
      context: .
      dockerfile: Dockerfile.sagemaker
    ports:
      - 8080:8080
    tty: true
