version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/code
    ports:
      - 3000:3000
    tty: true
  api:
    build: ./
    volumes:
      - ./:/code
    ports:
      - 3333:3333
    tty: true
