version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/code
      - ./aws/config:/root/.aws/config
      - ./aws/credentials:/root/.aws/credentials
    ports:
      - 3000:3000
    tty: true
  sagemaker:
    build:
      context: .
      dockerfile: Dockerfile.sagemaker
    ports:
      - 8080:8080
    tty: true
